# Generated by Django 5.2.16 on 2026-07-21 23:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("image", models.URLField(blank=True, default="")),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
